name = "ZulipStream"
uuid = "90cb88a9-eac6-49a0-8eb4-35a012fbf11f"
authors = ["Alberto Mercurio <alberto.mercurio96@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
